import type { Metadata } from "next";

import { Header } from "@/components/onboarding/header";
import { Footer } from "@/components/onboarding/footer";
import { StepSlider } from "@/components/onboarding/stepSlider";
import { StepSliderProvider } from "@/components/contexts/stepSliderContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OnboardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="mx-auto min-h-screen flex flex-col justify-between">
      <Header />
      <StepSliderProvider>
        <StepSlider
          defaultValue={[0]}
          max={100}
          step={1}
          className={"w-full rounded-none"}
        />
        <main className="flex-1 grid place-items-center bg-[#E5E7EB]">
          <section>{children}</section>
        </main>
      </StepSliderProvider>
      <Footer />
    </main>
  );
}
