import type { Metadata } from "next";

import { Header } from "@/components/onboarding/header";
import { Footer } from "@/components/onboarding/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OnboardingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto min-h-screen flex flex-col justify-between">
      <Header />
      <main className="flex-1 grid place-items-center bg-[#E5E7EB]">
        <section>{children}</section>
      </main>
      <Footer />
    </main>
  );
}
